<a href="https://colab.research.google.com/github/shreeomw/AI-Mafia-ML/blob/main/Solved_Numpy_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration

In [ ]:
np.__version__
np.show_config()

Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep139863411681952
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -fno-strict-aliasing
    commands: cc
    linker: ld.bfd
    linker args: -Wl,--strip-debug, -fno-strict-aliasing
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    linker args: -Wl,--strip-debug
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    name: cython
    versio

#### 3. Create a null vector of size 10

In [ ]:
n = np.zeros(10)
print(n)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array

In [ ]:
n = np.zeros((4,4))
print('%d-size of n'%(n.size))

16-size of n


#### 5.  How to get the documentation of the numpy add function from the command line?

In [ ]:
np.add?

#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [ ]:
n = np.zeros(10)
n[4] =1
print(n)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49

In [ ]:
n = np.array(range(10,50))
print(n)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last)

In [ ]:
n = np.array(range(10,50))
n = n[::-1]
print(n)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
n = np.array(range(0,9))
n = n.reshape(3,3)
print(n)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [ ]:
n = np.array([1,2,0,0,4,0])
print(np.nonzero(n))

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix

In [ ]:
n = np.eye(3)
print(n)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values

In [ ]:
n = np.random.random((3,3,3))
print(n)

[[[3.82537483e-01 8.08006403e-01 7.84368571e-02]
  [1.80462104e-01 4.30627912e-05 3.15894224e-01]
  [3.62308865e-01 2.92517938e-01 8.79753524e-01]]

 [[2.27093635e-01 5.72054105e-01 4.04886420e-01]
  [1.85039790e-01 5.56252643e-01 7.03738526e-01]
  [8.53752714e-01 2.09070543e-02 6.04549996e-01]]

 [[5.58060542e-01 3.12111500e-01 4.55555506e-02]
  [5.48179067e-01 1.08592046e-01 4.02640112e-01]
  [7.06117495e-01 5.10815793e-01 9.18019662e-01]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [ ]:
n = np.random.random((10,10))
print(n)
print(np.max(n))
print(np.min(n))

[[0.93828259 0.3726559  0.42013533 0.66222297 0.81759278 0.21539673
  0.72599044 0.40005705 0.46298524 0.04520393]
 [0.75470917 0.59288387 0.33258174 0.94179711 0.06957262 0.96690732
  0.10045636 0.80008805 0.11901695 0.40942887]
 [0.20822033 0.22740846 0.31673348 0.97070251 0.26947882 0.78618157
  0.64083887 0.20855144 0.76395121 0.70053625]
 [0.00260356 0.77466073 0.07144792 0.68972962 0.65484358 0.66256588
  0.84408199 0.09373973 0.0796352  0.70573381]
 [0.77238413 0.69118934 0.47895656 0.36066897 0.20230128 0.08374647
  0.238921   0.40419594 0.61912326 0.29191647]
 [0.70006201 0.83921479 0.48044221 0.18373849 0.64077585 0.25587306
  0.53070139 0.92013479 0.10641844 0.24715018]
 [0.1095855  0.70347827 0.50488701 0.8385862  0.25324914 0.24838757
  0.76388961 0.97128831 0.09261203 0.54054603]
 [0.49724223 0.45118256 0.01315789 0.88187484 0.17363755 0.05137453
  0.29278661 0.25295735 0.96799046 0.32411882]
 [0.89017274 0.52421742 0.83751879 0.73340921 0.54090382 0.51458127
  0.67545026

#### 14. Create a random vector of size 30 and find the mean value

In [ ]:
n = np.random.random(30)
print(n.mean())
print(n)

0.5750503291573268
[0.18889131 0.03700909 0.95060744 0.88547296 0.58245822 0.28253937
 0.04005849 0.85475707 0.44509684 0.91076689 0.92382398 0.80887482
 0.86800682 0.75182145 0.51531465 0.02690191 0.60181706 0.25874872
 0.89869212 0.72278417 0.47186964 0.50099314 0.84934937 0.49321574
 0.74460295 0.29622627 0.29613754 0.9105624  0.51783971 0.61626974]


#### 15. Create a 2d array with 1 on the border and 0 inside

In [ ]:
n = np.ones((10,10))
n[1:-1,1:-1] = 0 #explain
print(n)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array?

In [ ]:
n = np.ones((5,5))
n = np.pad(n, pad_width=1, mode='constant', constant_values=0)
print(n)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
0 * np.nan

True

In [ ]:
np.nan == np.nan

False

In [ ]:
np.inf > np.nan

False

In [ ]:
np.nan - np.nan

nan

In [ ]:
np.nan in set([np.nan])

True

In [ ]:
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [ ]:
n = np.zeros((5,5))
n = np.diag(1+np.arange(4),k=-1)
print(n)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [ ]:
n = np.zeros((8,8))
for i in range(8):
    for j in range(8):
        if (i+j)%2 == 0:
            n[i,j] = 1
print(n)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [ ]:
n = np.unravel_index(100,(6,7,8))
print(n)

(1, 5, 4)
